version: '3'
services:
  db_postgresql:
    image: postgres:latest
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env